Coding Partner Review
Yordinia/Todo-list-code-review pull request #1
Opened 2023-05-08 08:58 UTC by Yordinia

Hi Prosper Kesssie,

- [ ] Please review the **feature** branch based on the clean code principals of microverse.

2023-05-08 14:02 UTC, kessie2862 requested changes
# STATUS: CHANGES REQUIRED ♻

## Hi @Yordinia 👋

Good job so far!
There are some issues that you still need to work on but you are almost there!

- [ ] Highly organized code. ✔️
- [ ] GitHub flow is followed. ✔️
- [ ] DRY, YAGNI, and KISS rules are followed.
- [ ] Professional README file. ✔️
- [ ] No linter errors. ✔️

## Changes ♻
Check the comments below and make the required changes.
Submit for a re-review when you're done.

Thanks 😊

2023-05-08 14:02 UTC, kessie2862 commented on modules/draggable.js
> +}
I will suggest you use the ES6 arrow function syntax for this `finilizeDrag` function

2023-05-08 14:02 UTC, kessie2862 commented on modules/draggable.js
> +}
As indicated above, I will again suggest you use the ES6 arrow function syntax for this `toggleDrag` function as well.

2023-05-08 14:02 UTC, kessie2862 commented on modules/styling-purpose.js
> +}
Again, kindly use the ES6 arrow function syntax for the `classOn`, `classOff`, and `hideCursor` functions

2023-05-08 14:50 UTC, Yordinia commented on modules/draggable.js
> +}
Thanks I will @kessie2862

2023-05-08 14:50 UTC, Yordinia commented on modules/draggable.js
> +}
Thanks I will @kessie2862

2023-05-08 14:51 UTC, Yordinia commented
Thank @kessie2862 , we'll do.

2023-05-08 14:51 UTC, Yordinia commented
Thank @kessie2862 , we'll do.

2023-05-09 08:49 UTC, Yordinia commented on modules/styling-purpose.js
> +}
Hi @kessie2862 

Unfortunately, I couldn't change all the functions into ES6 arrow Functions.
As you can see below
![image](https://user-images.githubusercontent.com/75666332/237044280-c018a1c1-5ccd-44a0-be8d-2b7530139331.png)
- Changing that into arrow forced me not to use it as a class. (There was an automatic conversion of function to class if it wasn't arror function.)

- Thus,, did not change that one into what you requested. (Even tho  you didn't specificly requested me to change that code block.)

- Im just sharing for conversation and knowledge sake!

 **Thanks**
@Yordinia

2023-05-09 15:23 UTC, kessie2862 approved these changes
Hi @Yordinia 👋

Great job working on the feedback from the previous review. 

# STATUS APPROVED ✔

#### Your project is complete! There is nothing else to say other than... it's time to merge it 🔗 🚢
#### Congratulations! 🎉

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

## Important Notes 📝
Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2023-05-09 15:24 UTC, kessie2862 commented on modules/styling-purpose.js
> +}
That's fine. It's quite understandable

2023-05-11 09:53 UTC, merged